# This is a basic workflow to help you get started with Actions

name: Update workflow

# Controls when the workflow will run
on:
  push:
    branches: [master]
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
              cd jmjames37.github.io
              git pull
              cp ./* ../../pub/
